# ansible-playbook playbook.yml -u ubuntu --private-key IaC-Prod -i ../Infra/hosts.yml
---
-
  hosts: alura

  remote_user: ubuntu
  become: yes

  vars:
    - caminho_base: /home/ubuntu/projeto01

  tasks:
    - name: Instalar Python3, VirtualENV
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - virtualenv

    - name: Remover symlink do python
      file:
        path: "/usr/bin/python"
        state: absent

    - name: Add symlink pro python = python3
      file:
        src: "/usr/bin/python3"
        dest: "/usr/bin/python"
        state: link

    - name: Git Clone do projeto
      git:
        repo: https://github.com/alura-cursos/clientes-leo-api.git
        dest: {{ caminho_base }}
        version: master # A Branch
        force: yes # Vai sempre sobrescrever se já existir um clone anterior

    - name: Instalando dependencias - Apenas no virtualenv
      pip:
        virtualenv: {{ caminho_base }}/venv
        requirements: {{ caminho_base }}/requirements.txt

    - name: Alterando ALLOWED_HOSTS
      lineinfile:
        path: {{ caminho_base }}/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        # Se o regex não achar nada, não mexe no arquivo
        backrefs: yes

    - name: Configurar o DB + Subir aplicação
      shell: "{{ lookup('template', 'script.j2') }}"
      args:
        executable: /bin/bash
...