# ansible-playbook playbook.yml -u ubuntu --private-key alura.pem -i hosts.yml
---
-
  hosts: alura
  remote_user: ubuntu
  become: yes

  tasks:
#    - name:
#      copy:
#        dest: /home/ubuntu/index.html
#        content: <h1>Feito com Ansible</h1>

#    - name:
#      shell: "busybox httpd -f -p 8080"

    - name: Instalar Python3, VirtualENV
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - virtualenv

    - name: Remover symlink do python
      file:
        path: "/usr/bin/python"
        state: absent

    - name: Add symlink pro python = python3
      file:
        src: "/usr/bin/python3"
        dest: "/usr/bin/python"
        state: link

    - name: Instalando dependencias - Apenas no virtualenv
      pip:
        virtualenv: /home/ubuntu/projeto01/venv
        name:
          - django
          - djangorestframework

    - name: Iniciando projeto
      shell: '. /home/ubuntu/projeto01/venv/bin/activate; django-admin startproject setup 0.0.0.0:8080'

    - name: Alterando ALLOWED_HOSTS
      lineinfile:
        path: /home/ubuntu/projeto01/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        # Se o regex não achar nada, não mexe no arquivo
        backrefs: yes
...